import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import Link from "next/link";
import { ArrowRight, ShoppingBag, Landmark, Building, Truck, Activity, Briefcase, Sparkles, CheckCircle2 } from "lucide-react";

export const metadata: Metadata = {
  title: "Industry Solutions & Sector Expertise",
  description:
    "Explore how our business and technology solutions are tailored around the operational realities of Retail, FinTech, Real Estate, Logistics, Healthcare, and B2B services.",
};

const industries = [
  {
    id: "retail",
    icon: ShoppingBag,
    name: "Retail & E-Commerce",
    headline: "Unified Omnichannel Fulfillment & High-Volume Customer Operations",
    challenges: [
      "Fragmented customer inquiries across WhatsApp, social channels, and web stores.",
      "Inventory desynchronization between physical stores, warehouses, and online platforms.",
      "Manual order verification, returns management, and delivery exception handling.",
    ],
    solutions: [
      "Centralized omnichannel conversation routing with automated order status lookups.",
      "Real-time bidirectional ERP and e-commerce inventory sync pipelines.",
      "Automated customer notification flows for abandoned carts, shipping milestones, and reorders.",
    ],
    impact: "Shorter response times, reduced order fulfillment errors, and higher repeat customer LTV.",
  },
  {
    id: "fintech",
    icon: Landmark,
    name: "Financial Services & FinTech",
    headline: "Secure Onboarding Pipelines, Compliance Workflows & Systems Modernization",
    challenges: [
      "Strict regulatory compliance and data governance requirements.",
      "Manual KYC verification processes causing high friction and onboarding abandonment.",
      "Legacy core banking systems that resist modern web and mobile API integrations.",
    ],
    solutions: [
      "Automated document processing and identity validation pipelines.",
      "Secure API integration layers connecting legacy mainframes with modern front-ends.",
      "Comprehensive audit logging, role-based access control, and data encryption.",
    ],
    impact: "Faster client onboarding, reduced compliance risk, and modern digital customer touchpoints.",
  },
  {
    id: "real-estate",
    icon: Building,
    name: "Real Estate & PropTech",
    headline: "Automated Lead Qualification, Sales Operations & Tenant Portals",
    challenges: [
      "High inbound inquiry volume with delayed agent follow-ups and lost buyer leads.",
      "Unstructured lead tracking across multiple property portals and broker networks.",
      "Manual tenant maintenance requests and lease renewal paperwork.",
    ],
    solutions: [
      "Instant 24/7 lead qualification and automated broker assignment via messaging channels.",
      "Custom CRM sync and centralized inventory management for unit availability.",
      "Self-service tenant portals for maintenance ticketing and digital document submission.",
    ],
    impact: "Higher lead-to-viewing conversion rates and streamlined property management operations.",
  },
  {
    id: "logistics",
    icon: Truck,
    name: "Logistics & Supply Chain",
    headline: "Real-Time Dispatch Visibility, Carrier Integration & Event Automation",
    challenges: [
      "Operational blind spots across multi-carrier dispatch and last-mile delivery.",
      "High customer support costs generated by repetitive 'Where is my order?' inquiries.",
      "Manual manifest reconciliations and delayed proof-of-delivery updates.",
    ],
    solutions: [
      "Custom carrier integration middleware unifying multiple 3PL/courier APIs.",
      "Automated real-time tracking webhooks and customer messaging triggers.",
      "Centralized operations dashboards for fleet status, exception monitoring, and SLA tracking.",
    ],
    impact: "Zero manual tracking lookups, reduced dispatch exceptions, and clear supply chain transparency.",
  },
  {
    id: "healthcare",
    icon: Activity,
    name: "Healthcare & Life Sciences",
    headline: "Patient Engagement Automation, Scheduling & Secure Integration Layers",
    challenges: [
      "High rate of patient appointment no-shows and administrative scheduling phone calls.",
      "Disconnected Electronic Medical Record (EMR) databases requiring redundant data entry.",
      "Strict data privacy regulations demanding HIPAA-compliant communication.",
    ],
    solutions: [
      "Automated appointment scheduling, reminder sequences, and confirmation workflows.",
      "Secure integration pipelines between practice management software and patient communications.",
      "Encrypted patient intake and document collection portals.",
    ],
    impact: "Fewer appointment drop-offs, lowered administrative overhead, and elevated patient satisfaction.",
  },
  {
    id: "b2b",
    icon: Briefcase,
    name: "B2B & Professional Services",
    headline: "Client Lifecycle Platforms, Automated Workflows & Billing Integration",
    challenges: [
      "Extended enterprise sales cycles and manual proposal follow-ups.",
      "Siloed communication between account managers, consulting teams, and finance.",
      "Disconnected time-tracking, invoicing, and project milestone approvals.",
    ],
    solutions: [
      "Bespoke client collaboration portals with embedded milestone approvals.",
      "Automated billing triggers syncing CRM project completions with accounting systems.",
      "Centralized document workflows and contract execution integrations.",
    ],
    impact: "Accelerated cash collection, eliminated administrative billing disputes, and transparent client reporting.",
  },
];

export default function IndustriesPage() {
  return (
    <div className="bg-white text-slate-900 min-h-screen flex flex-col font-sans">
      <Navbar />

      <main className="flex-1 pt-32 pb-24">
        {/* Page Hero */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mb-20">
          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 border border-blue-100 px-3.5 py-1.5 rounded-full text-xs font-bold uppercase tracking-wider mb-6">
              <Sparkles size={13} />
              <span>Industry Focus</span>
            </div>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-slate-950 tracking-tight leading-[1.12] mb-6">
              Technology That Understands Your Industry.
            </h1>
            <p className="text-lg sm:text-xl text-slate-600 leading-relaxed">
              We design and engineer business solutions that reflect the operational reality, regulatory standards, and customer dynamics of each specific sector.
            </p>
          </div>
        </section>

        {/* Industry Cards */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-12">
            {industries.map((ind) => {
              const Icon = ind.icon;
              return (
                <div
                  key={ind.id}
                  id={ind.id}
                  className="bg-slate-50/80 border border-slate-200/80 rounded-3xl p-8 sm:p-12 hover:bg-white hover:border-blue-500/30 hover:shadow-lg transition-all scroll-mt-28"
                >
                  <div className="flex flex-col lg:flex-row items-start justify-between gap-8 mb-8 pb-8 border-b border-slate-200/80">
                    <div className="flex items-center gap-4">
                      <div className="w-14 h-14 rounded-2xl bg-blue-600 text-white flex items-center justify-center shadow-xs">
                        <Icon size={28} />
                      </div>
                      <div>
                        <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-950 tracking-tight">
                          {ind.name}
                        </h2>
                        <p className="text-sm font-semibold text-blue-600 mt-1">
                          {ind.headline}
                        </p>
                      </div>
                    </div>

                    <Link
                      href="/contact"
                      className="bg-white hover:bg-slate-50 text-slate-800 border border-slate-200 px-5 py-2.5 rounded-xl font-bold text-xs transition-all flex items-center gap-2 shadow-2xs group flex-shrink-0"
                    >
                      <span>Discuss {ind.name} Project</span>
                      <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
                    </Link>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-6">
                    {/* Operational Challenges */}
                    <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-2xs">
                      <span className="text-xs font-bold uppercase tracking-wider text-red-600 block mb-3">
                        Common Sector Bottlenecks
                      </span>
                      <ul className="space-y-2.5">
                        {ind.challenges.map((c, idx) => (
                          <li key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-700">
                            <span className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 flex-shrink-0" />
                            <span>{c}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    {/* Tailored Solutions */}
                    <div className="bg-white border border-slate-200/80 rounded-2xl p-6 shadow-2xs">
                      <span className="text-xs font-bold uppercase tracking-wider text-blue-600 block mb-3">
                        How Our Solutions Solve It
                      </span>
                      <ul className="space-y-2.5">
                        {ind.solutions.map((s, idx) => (
                          <li key={idx} className="flex items-start gap-2.5 text-xs sm:text-sm text-slate-700 font-medium">
                            <CheckCircle2 size={16} className="text-blue-600 flex-shrink-0 mt-0.5" />
                            <span>{s}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* Business Impact Strip */}
                  <div className="bg-blue-50/70 border border-blue-100 rounded-2xl px-6 py-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
                    <span className="text-xs font-bold uppercase tracking-wider text-blue-900">
                      Primary Commercial Impact:
                    </span>
                    <span className="text-xs sm:text-sm font-semibold text-blue-800">
                      {ind.impact}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* Bottom CTA */}
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-20">
          <div className="bg-slate-950 text-white rounded-3xl p-8 sm:p-12 flex flex-col md:flex-row items-center justify-between gap-6 border border-slate-800">
            <div>
              <h3 className="text-2xl font-bold mb-2">
                Operating in another specialized sector?
              </h3>
              <p className="text-slate-400 text-sm">
                Our engineering and business architecture methodology applies across any data-driven, operational environment.
              </p>
            </div>
            <Link
              href="/contact"
              className="flex-shrink-0 bg-blue-600 hover:bg-blue-700 text-white px-7 py-3.5 rounded-xl font-bold text-xs transition-all flex items-center gap-2 group"
            >
              <span>Consult With an Industry Architect</span>
              <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
            </Link>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
